### ISSUE TITLE
Set up PI Emulation

### ISSUE THREAD

**Issue by kdehaan** [ECE-492-W2020-Group-6/smart-blinds-rpi#11]
Allow for testing and development without having a physical raspberry PI available

GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by ishchow** [comment]
Look into QEMU

**Comment by ishchow** [comment]
GanttStart: 2020-01-22
GanttDue: 2020-01-29

**Comment by ishchow** [comment]
@kdehaan While I was working on #41, I was able to dockerize all the rpi code into an ARM image and run the ARM image on my host machine (which has an x86 CPU). I can run the docker image for the rpi code using QEMU in user mode, so that the sys calls made in the docker image are translated to the host machine's CPU architecture. This effectively allows emulation of the rpi code as if it was running on the raspberry pi but without creating a VM. I wrote a [wiki page](https://github.com/ECE-492-W2020-Group-6/smart-blinds-rpi/wiki/Development-Testing-Emulation-using-Docker-Buildx) that has instructions for setting this up.

If you think the docker method effectively does the same thing as this issue, then can you please close it?

**Comment by kdehaan** [comment]
If anything, this is a better solution than regular emulation. Closed!
